### ISSUE TITLE
Add a splash screen

### ISSUE THREAD

**Issue by jkhoeini** [EntTM/etm#2]
Make a splash which resolves nicely to the entrance page.

**Comment by HosseinNikpour** [comment]
اقا من نمیتونم لاگین کنمشما لاگین کردین 

```
 On Wednesday, August 19, 2015 11:34 AM, Mohammad Sadegh Khoeini <notifications@github.com> wrote:
```

 Make a splash which resolves nicely to the entrance page.—

**Comment by jkhoeini** [comment]
شما باید برای این یک issue جدید بسازید. ;-)
ضمنا من بدون مشکل لاگین می‌کنم. :p
